### ISSUE TITLE
nametag displaying on entitiesd

### ISSUE THREAD

**Issue by brandyyn** [kotmatross28729/Shader-fixer#11]
![image](https://github.com/user-attachments/assets/26323fcf-cdf8-492f-9c0b-0d4d14fcc71b)
![image](https://github.com/user-attachments/assets/a01b6258-931e-4fef-b9ff-8fada7709af2)

**Comment by kotmatross28729** [comment]
What do you mean? shadow?

**Comment by brandyyn** [comment]
> What do you mean? shadow?

yeah you can see the text's shadow on the villager's head

**Comment by kotmatross28729** [comment]
In theory this is how it is intended, but I can try disabling the depth buffer when rendering

**Comment by kotmatross28729** [comment]
Fixed: https://github.com/kotmatross28729/Shader-fixer/releases/download/3.2-PRE/shadersfixer-3.2.jar
