### ISSUE TITLE
Request: Fix shaders being applied to Toro Health floating damage numbers 

### ISSUE THREAD

**Issue by huihiuhuai** [kotmatross28729/Shader-fixer#6]
[Toro Health](https://github.com/GTNewHorizons/ToroHealth)
![image](https://github.com/user-attachments/assets/6dc30f66-fa42-4af3-b392-b7ce87bc6b0d)
![image](https://github.com/user-attachments/assets/05ffc64a-678e-4e6e-9ad1-e689adcaf14e)

**Comment by kotmatross28729** [comment]
But... what's the error? Toro Health numbers have a bloom effect on it? If you mean this, then this is not error, this is how it should be (?), you can disable bloom effect in the shader config. (Or you mean another error?)

**Comment by huihiuhuai** [comment]
Yes, i mean the bloom effect. Should the bloom
effect be used on particles?

**Comment by kotmatross28729** [comment]
Yeah, the bloom effect should be on the particles, this is part of the shaders. Of course, you can disable it for some things separately, but you need to edit the shader files yourself (and know GLSL), but I don’t think it’s that critical?

**Comment by huihiuhuai** [comment]
it is controlled by "drity lens" shader option
